# Generated by Django 6.0.6 on 2026-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante'), ('visitante', 'Visitante')], default='visitante', max_length=20),
        ),
    ]
