# Generated by Django 6.0.6 on 2026-06-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_equipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante'), ('visitante', 'Visitante')], max_length=20, unique=True)),
                ('permisos', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Permiso de rol',
                'verbose_name_plural': 'Permisos de roles',
            },
        ),
    ]
