# Generated by Django 6.0.7 on 2026-08-01 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_permisorol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('programa', models.CharField(max_length=200)),
                ('jornada', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='permisorol',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante'), ('aprendiz', 'Aprendiz'), ('instructor', 'Instructor')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vigilante', 'Vigilante'), ('aprendiz', 'Aprendiz'), ('instructor', 'Instructor')], default='aprendiz', max_length=20),
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('bloque', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FichaAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.aula')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ficha')),
            ],
            options={
                'unique_together': {('ficha', 'aula')},
            },
        ),
        migrations.CreateModel(
            name='InstructorFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.ficha')),
                ('instructor', models.ForeignKey(limit_choices_to={'rol': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('instructor', 'ficha')},
            },
        ),
    ]
