# Generated by Django 6.0.7 on 2026-08-01 03:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_ficha_alter_permisorol_rol_alter_usuario_rol_aula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='aprendices',
            field=models.ManyToManyField(limit_choices_to={'rol': 'aprendiz'}, related_name='fichas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fichaaula',
            name='jornada',
            field=models.CharField(default='Mañana', max_length=20),
        ),
    ]
